version: "2"

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "5552:5552/tcp"
#    volumes:
#      # nginx 설정파일을 로컬의 ./nginx 폴더에 넣어준 후 연결
#      - ./nginx:/etc/nginx/conf.d
#
#      # Django와 사용하는 static 폴더
#      - ./static:/staticfiles
#    depends_on:
#      - django

  django:
    environment:
      - DJANGO_SECRET=django-insecure-dgbp!q_yauu-j)udgh*wa(ml-epuw#_&8hh=afgs_ocy_)#vtl
      - DB_USERNAME=root
      - DB_PASSWORD=d@12YinYang
    ports:
      - 5552:5552
    # docker hub 업로드한 이미지
    image: korshika/stockmanager-back-django:latest
    container_name: StockManager-Django-Server

    # gunicorn를 사용하여 8000번 포트로 서비스
    command: >
      bash -c "pip list
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && gunicorn StockManager.wsgi -b 0.0.0.0:5552 "

#    volumes:
#      # nginx와 사용하는 static 폴더
#      - ./static:/usr/src/app/staticfiles
    expose:
      - "5552"