# Generated by Django 3.2.9 on 2021-12-18 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appStockAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_regday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
