# Generated by Django 3.2.9 on 2022-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockAccount', '0002_auto_20220111_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_registered', models.DateTimeField(auto_now=True)),
                ('is_payedOn', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyStocks',
        ),
        migrations.DeleteModel(
            name='UserMeta',
        ),
    ]
