# Generated by Django 3.2.9 on 2022-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockAccount', '0003_auto_20220111_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
