# Generated by Django 3.2.9 on 2022-01-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockAccount', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
