# Generated by Django 3.2.9 on 2022-01-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStockAccount', '0007_remove_user_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
