# Generated by Django 3.2.9 on 2021-12-06 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('stock_market_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockItemList',
            fields=[
                ('stock_item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('stock_item_code', models.CharField(max_length=200)),
                ('stock_market_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockmarket')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(default=datetime.datetime(2021, 12, 6, 22, 23, 37, 600898), null=True)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('stock_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlist')),
            ],
        ),
    ]
