# Generated by Django 3.2.9 on 2021-12-26 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockLastUpdateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockSection',
            fields=[
                ('section_integer', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(default='DummyName', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockTick',
            fields=[
                ('stock_tick', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('stock_marketName', models.CharField(max_length=200)),
                ('stock_isInfoAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockItemListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.BigIntegerField(default=0)),
                ('section_name', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocksection')),
                ('stock_tick', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick')),
            ],
        ),
        migrations.CreateModel(
            name='StockItemListName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(default='DummyName', max_length=200)),
                ('stock_tick', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('open', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('div', models.FloatField(default=0.0)),
                ('per', models.FloatField(default=0.0)),
                ('pbr', models.FloatField(default=0.0)),
                ('roe', models.FloatField(default=0.0)),
                ('stock_map_section', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlistsection')),
                ('stock_name', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlistname')),
            ],
        ),
    ]
