# Generated by Django 3.2.9 on 2021-12-12 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTick',
            fields=[
                ('stock_tick', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('stock_marketName', models.CharField(max_length=200)),
                ('stock_isInfoAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockItemListName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(default='Dummy', max_length=200)),
                ('stock_tick', models.ForeignKey(default='dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('open', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('per', models.FloatField(default=0.0)),
                ('pbr', models.FloatField(default=0.0)),
                ('roe', models.FloatField(default=0.0)),
                ('roa', models.FloatField(default=0.0)),
                ('stock_name', models.ForeignKey(default='dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlistname')),
            ],
        ),
    ]
