# Generated by Django 3.2.9 on 2021-12-08 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 8, 19, 5, 38, 98051), null=True),
        ),
    ]
