# Generated by Django 3.2.9 on 2021-12-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='roa',
        ),
    ]
