# Generated by Django 3.2.9 on 2021-12-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_name',
            field=models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlistname'),
        ),
        migrations.AlterField(
            model_name='stockitemlistname',
            name='stock_name',
            field=models.CharField(default='DummyName', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockitemlistname',
            name='stock_tick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick'),
        ),
    ]
