# Generated by Django 3.2.9 on 2021-12-08 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0002_alter_stockitem_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
