# Generated by Django 3.2.9 on 2021-12-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0002_remove_stockitem_roa'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='div',
            field=models.FloatField(default=0.0),
        ),
    ]
