# Generated by Django 3.2.9 on 2021-12-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0002_auto_20211212_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemlistname',
            name='stock_tick',
            field=models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick'),
        ),
    ]
