# Generated by Django 3.2.9 on 2021-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0003_stockitem_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='total_sum',
            field=models.BigIntegerField(default=0),
        ),
    ]
