# Generated by Django 3.2.9 on 2021-12-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0003_alter_stockitem_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTick',
            fields=[
                ('stock_tick', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('stock_marketName', models.CharField(max_length=200)),
                ('stock_isInfoAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='stockitemlist',
            old_name='stock_item_name',
            new_name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='stock_item_name',
        ),
        migrations.RemoveField(
            model_name='stockitemlist',
            name='stock_item_code',
        ),
        migrations.RemoveField(
            model_name='stockitemlist',
            name='stock_market_name',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='pbr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='per',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='roa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='roe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_name',
            field=models.ForeignKey(default='dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlist'),
        ),
        migrations.DeleteModel(
            name='StockMarket',
        ),
        migrations.AddField(
            model_name='stockitemlist',
            name='stock_tick',
            field=models.ForeignKey(default='dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick'),
        ),
    ]
