# Generated by Django 3.2.9 on 2021-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0003_alter_stockitemlistname_stock_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='total_sum',
            field=models.IntegerField(default=0),
        ),
    ]
