# Generated by Django 3.2.9 on 2021-12-18 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appStockInfo', '0004_stockitem_total_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLastUpdateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
