# Generated by Django 3.2.9 on 2022-01-02 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appStockInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('stock_name', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitemlistname')),
                ('stock_tick', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick')),
            ],
        ),
    ]
