# Generated by Django 3.2.9 on 2021-12-27 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appStockInfo', '0002_alter_stockitem_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField(default=0)),
                ('stock_tick', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stocktick')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_percent', models.FloatField(default=0)),
                ('stock_item', models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, to='appStockInfo.stockitem')),
            ],
        ),
    ]
