# Generated by Django 3.2.9 on 2022-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStockPrediction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpredictionhistory',
            name='initial_close',
            field=models.FloatField(default=0),
        ),
    ]
