# Generated by Django 3.1.7 on 2021-02-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price_now', models.FloatField()),
                ('price_compared', models.FloatField()),
                ('price_ratio', models.FloatField()),
                ('price_straight', models.FloatField()),
                ('total_stock_sum', models.IntegerField()),
                ('total_stock_num', models.IntegerField()),
                ('total_foreign_ratio', models.FloatField()),
                ('trade_sum', models.IntegerField()),
                ('per', models.FloatField()),
                ('roe', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
