# Generated by Django 3.1.7 on 2021-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseapp', '0002_auto_20210227_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklistdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
